import { createSlice } from '@reduxjs/toolkit'
import img14 from '../images/img14.jpg';



const initialValue = [
    {   
      id: 1,
      name: "Chocolate Cake",
      preparation_time: 60,
      ingredients: ["Flour", "Cocoa powder", "Sugar", "Eggs", "Baking powder", "Milk", "Butter", "Vanilla extract"],
      category: "milky",
      is_favorite: "false",
      img: img14,
    },
    {   
      id: 2,
      name: "Vegetable Soup",
      preparation_time: 40,
      ingredients: ["Carrots", "Celery", "Potatoes", "Onions", "Garlic", "Vegetable broth", "Parsley", "Salt", "Pepper"],
      category: "parve",
      is_favorite: "false",
      img: img14,
    },
    {   
      id: 3,
      name: "Pasta Alfredo",
      preparation_time: 30,
      ingredients: ["Pasta", "Heavy cream", "Butter", "Parmesan cheese", "Garlic", "Salt", "Pepper", "Parsley"],
      category: "milky",
      is_favorite: "false",
      img: img14,
    },
    {   
      id: 4,
      name: "Quinoa Salad",
      preparation_time: 25,
      ingredients: ["Quinoa", "Cherry tomatoes", "Cucumber", "Red onion", "Olive oil", "Lemon juice", "Mint"],
      category: "parve",
      is_favorite: "false",
      img: img14,
    },
    {   
      id: 5,
      name: "Shakshuka",
      preparation_time: 20,
      ingredients: ["Eggs", "Tomatoes", "Onion", "Garlic", "Red pepper", "Paprika", "Cumin", "Salt", "Parsley"],
      category: "parve",
      is_favorite: "false",
      img: img14,
    },
    {   
      id: 6,
      name: "Vegetarian Sushi",
      preparation_time: 50,
      ingredients: ["Sushi rice", "Nori sheets", "Cucumber", "Carrot", "Avocado", "Soy sauce", "Rice vinegar"],
      category: "parve",
      is_favorite: "false",
      img: img14,
    },
    {   
      id: 7,
      name: "Mushroom Risotto",
      preparation_time: 45,
      ingredients: ["Arborio rice", "Mushrooms", "Onion", "Garlic", "Vegetable broth", "White wine", "Butter", "Parmesan cheese"],
      category: "milky",
      is_favorite: "false",
      img: img14,
    },
    {   
      id: 8,
      name: "Falafel",
      preparation_time: 30,
      ingredients: ["Chickpeas", "Onion", "Garlic", "Parsley", "Cumin", "Coriander", "Salt", "Pepper", "Flour"],
      category: "parve",
      is_favorite: "false",
      img: img14,
    },
    {   
      id: 9,
      name: "Cheese Omelette",
      preparation_time: 10,
      ingredients: ["Eggs", "Cheese", "Milk", "Salt", "Pepper"],
      category: "milky",
      is_favorite: "true",
      img: img14,
    },
    {   
      id: 10,
      name: "Hummus",
      preparation_time: 15,
      ingredients: ["Chickpeas", "Tahini", "Lemon juice", "Garlic", "Olive oil", "Salt"],
      category: "parve",
      is_favorite: "false",
      img: img14,
    },
    {   
      id: 11,
      name: "Greek Salad",
      preparation_time: 15,
      ingredients: ["Tomatoes", "Cucumber", "Red onion", "Feta cheese", "Olives", "Olive oil", "Oregano"],
      category: "milky",
      is_favorite: "false",
      img: img14,
    },
    {   
      id: 12,
      name: "Lentil Stew",
      preparation_time: 60,
      ingredients: ["Lentils", "Carrots", "Onions", "Garlic", "Tomatoes", "Vegetable broth", "Cumin", "Paprika"],
      category: "parve",
      is_favorite: "true",
      img: img14,
    },
    {   
      id: 13,
      name: "Spinach Pie",
      preparation_time: 50,
      ingredients: ["Spinach", "Feta cheese", "Phyllo dough", "Eggs", "Onion", "Salt", "Pepper"],
      category: "milky",
      is_favorite: "false",
      img: img14,
    },
    {   
      id: 14,
      name: "Sweet Potato Fries",
      preparation_time: 35,
      ingredients: ["Sweet potatoes", "Olive oil", "Salt", "Pepper", "Paprika"],
      category: "parve",
      is_favorite: "false",
      img: img14,
    },
    {   
      id: 15,
      name: "Fruit Salad",
      preparation_time: 10,
      ingredients: ["Apple", "Banana", "Orange", "Grapes", "Strawberries", "Mint", "Honey"],
      category: "parve",
      is_favorite: "true",
      img: img14,
    },
    {   
      id: 16,
      name: "Vegetable Stir-Fry",
      preparation_time: 20,
      ingredients: ["Broccoli", "Carrots", "Bell peppers", "Soy sauce", "Garlic", "Ginger"],
      category: "parve",
      is_favorite: "false",
      img: img14,
    },
    {   
      id: 17,
      name: "Cheesecake",
      preparation_time: 90,
      ingredients: ["Cream cheese", "Sugar", "Eggs", "Vanilla extract", "Butter", "Graham crackers"],
      category: "milky",
      is_favorite: "false",
      img: img14,
    },
    {   
      id: 18,
      name: "Roasted Vegetables",
      preparation_time: 40,
      ingredients: ["Zucchini", "Bell peppers", "Eggplant", "Onion", "Olive oil", "Salt", "Pepper"],
      category: "parve",
      is_favorite: "false",
      img: img14,
    },
    {   
      id: 19,
      name: "Banana Smoothie",
      preparation_time: 5,
      ingredients: ["Banana", "Milk", "Honey", "Ice cubes"],
      category: "milky",
      is_favorite: "false",
      img: img14,
    },
    {   
      id: 20,
      name: "Couscous Salad",
      preparation_time: 20,
      ingredients: ["Couscous", "Cucumber", "Tomatoes", "Mint", "Parsley", "Olive oil", "Lemon juice"],
      category: "parve",
      is_favorite: "false",
      img: img14,
    },
    {   
      id: 21,
      name: "Vegetable Quiche",
      preparation_time: 50,
      ingredients: ["Eggs", "Milk", "Cheese", "Broccoli", "Onions", "Pie crust", "Salt", "Pepper"],
      category: "milky",
      is_favorite: "false",
      img: img14,
    },
    {   
      id: 22,
      name: "Stuffed Peppers",
      preparation_time: 60,
      ingredients: ["Bell peppers", "Rice", "Tomatoes", "Onion", "Garlic", "Olive oil"],
      category: "parve",
      is_favorite: "false",
      img: img14,
    },
    {   
      id: 23,
      name: "Tomato Pasta",
      preparation_time: 25,
      ingredients: ["Pasta", "Tomato sauce", "Garlic", "Olive oil", "Basil"],
      category: "parve",
      is_favorite: "false",
      img: img14,
    },
    {   
      id: 24,
      name: "Vegetable Pizza",
      preparation_time: 45,
      ingredients: ["Pizza dough", "Tomato sauce", "Cheese", "Bell peppers", "Mushrooms"],
      category: "milky",
      is_favorite: "false",
      img: img14,
    },
    {   
      id: 25,
      name: "Apple Pie",
      preparation_time: 75,
      ingredients: ["Apples", "Sugar", "Cinnamon", "Pie crust", "Butter"],
      category: "milky",
      is_favorite: "false",
      img: img14,
    }
  ];
  
const RecipeSlice = createSlice({
    name:"Recipe",
    initialState: initialValue,
    reducers:{
        updateFavorite:(state,action)=>{    
            state[action.payload].is_favorite = "true";
        },
        addRecipe:(state,action)=>{
            state.push(action.payload)
        }
    }


})
export const {updateFavorite, addRecipe} = RecipeSlice.actions
export default RecipeSlice.reducer